### ISSUE TITLE
[Todo] - Accommodating non-API University Data Sources - Yale & Beyond

### ISSUE THREAD

**Issue by hydrosquall** [CampusData/campusdata.github.io#18]
If a University posts data relevant to the campus categories in non-API format, the `_data/rankings.yml` file should link to a page with links to those resources. 

For example, it's likely that course, sporting event, and food menu is available somewhere for most universities, even if not in friendly API format. Creating a page like this will enable non-technical volunteers to identify what data sources are missing. This way, campus data initiatives can differentiate between what existing data sources can be turned into RESTful APIs, and what data isn't being reported online at all. This separation will make it easier for technical and non-technical members to identify how to most effectively spend their time (ex technical members may write scrapers or move spreadsheets into databases; non-technical members can explore how to begin publishing data even if not in API format).

I'll get around to creating one for Yale in the near future, the below comment contains links to the sort of content that would go onto such a page for Yale. 

This paints a more descriptive picture of the state of online data for a university rather than marking "false" for everything there isn't an API for. Perhaps an intermediary symbol (say, a yellow circle, like a traffic light) could represent data that is published online regularly in a non-API friendly way.  

```yml
athletics: false # working with student athlete committee for  gametimes + locations.
    buildings: false # there is an office with the geoJSON polygon data for campus buildings
    courses: false #  ybb.yale.edu/ 
    #Course Scraper: yaledatascience.github.io/2015/01/13/spring-2015-preview/
    dining: false # not API but this is scrapable: http://www.yale.edu/dining/menu/todaysmenus.html
    events: false # there are several failed initiatives in this space
    housing: false # each residential college does own thing, use proprietary starportal
    library: false # Catalog search, reserve rooms, reserve equipment: 
    map: false # http://map.yale.edu/map/
    news: false # Official Campus News Feed vs Student Newspaper?
    people: false #scrapable if member of university: https://students.yale.edu/facebook/
    printers: false # Distributed Printing: http://ypps.yale.edu/blueprint-overview
    textbooks: false # scrape the "free and for sale" facebook group
    transit: false # proprietary shuttle service: http://yale.transloc.com/
    weather: false
    extras: null
    #Extras:
        # Student-built app for renting equipment from the library: https://reservations.yale.edu/bmec/
        # Campus Energy usage: http://java.facilities.yale.edu/energy/ 
    # Tenuous whether this is campus-specific, but included as data here may be relevant
        # Open clinical research data: http://yoda.yale.edu/
        # Municipal OpenData: http://www.ctdatahaven.org/
        # State OpenData: http://www.ctdata.org/
```

Created using the comments that were drafted from this pull request: https://github.com/CampusData/campusdata.github.io/pull/16
